"""Describe the changes made

Revision ID: f1a7406ba33b
Revises: 59d40acffa15
Create Date: 2024-11-27 16:34:41.955644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a7406ba33b'
down_revision = '59d40acffa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=256), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.Column('object_id', sa.INTEGER(), nullable=False),
    sa.Column('x1', sa.FLOAT(), nullable=False),
    sa.Column('y1', sa.FLOAT(), nullable=False),
    sa.Column('x2', sa.FLOAT(), nullable=False),
    sa.Column('y2', sa.FLOAT(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prediction2')
    op.drop_table('prediction1')
    # ### end Alembic commands ###
